### ISSUE TITLE
Errors in 2024 datasets

### ISSUE THREAD

**Issue by babi00** [toUpperCase78/formula1-datasets#2]
I would like to highlight two errors:

1. Formula1_2024season_qualifyingResults.csv line 113: "Maimi" instead of "Miami"
2. Formula1_2024season_raceResults.csv line 47: "Aston Matin Aramco Mercedes" instead of "Aston Martin Aramco Mercedes"

**Comment by toUpperCase78** [comment]
Hi there,
Thank you for notifying me these typos in 2024 season datasets. Now they were corrected.
